services:
  backend:
    build:
      context: ./backend
    container_name: rock-vs-mine-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    networks:
      - rock-vs-mine-net

  frontend:
    build:
      context: ./rock-vs-mine-front
    container_name: rock-vs-mine-front
    ports:
      - "3000:80" # Map host 3000 to container 80 (Nginx)
    environment:
      VITE_API_URL: http://backend:8000
    networks:
      - rock-vs-mine-net
    depends_on:
      - backend

networks:
  rock-vs-mine-net:
    driver: bridge